### ISSUE TITLE
 I found an issue here /

### ISSUE THREAD

**Issue by Xshelton** [puolival/multipy#1]
File "C:\Users\shelton\AppData\Local\Programs\Python\Python36\lib\site-packages\multipy\fwer.py", line 28, in <module>
    from logger import log_fwer_analysis
ImportError: cannot import name 'log_fwer_analysis'
 Here came an error:
So the first time when I ran the example
"from multipy.data import neuhaus
from multipy.fwer import sidak

pvals = neuhaus()
significant_pvals = sidak(pvals, alpha=0.05)
"it said that no module named logger
then I piped install logger 
here came another error
so I don;t know how to fix it now.

**Comment by puolival** [comment]
Thanks for pointing this out! I will look into it soon.
